language: python
sudo: false

env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "vxwIdGm1WhAad542sAyVjpwkFsv8Z68KwYqoj8//ndA7FklIJys0F6ciYUVToNh8680CDDg05uSgucO4anKWnhU/eiq3ObLPYZivJBmeQyjI3Z5LbpCvO9vJdgENFZeCT9LPz6yv2y8ez9sweM/vocXV0uzkKrYxGLneoLI/Jr1fPJyocI0QUORZzHhzFsuawSB+BgqwmkEJaSJn5ja85nIkhdEgkAWiWPvCfi2P10kn+cOl635NoC0GVZ65WpblowiQgZDEiBj/uAjP7oCoxIY6Mlx3xvNL9GGbAy85CcB9Ntu58CQDep+cROVJ9YcQrxZjFCx7KPAHLaiQkgZAl/nj9vkXVXByY0iORbREyq4o5R5Bma/Ytw7epzf8LmmPw+K2lC62uNS1ZYhvT58gH43TzSWLxvUydUe2nrPvUNZXTz6ypu0cpwh4gC/VtH532O6E+CWHXsl0w8pVIoVlweWoa8XWX9Xxyz9XziRJ1D76To6xsvaFDWdEFCPSNrxCj2wXCbIgizi/uYDLXZBVAoXLNoiVswpUyjoyLM0UqOpucQGU40n8MSRQzduJyh2rwm/zbzQMpU0qwYy6sovEoHwzkNqTNJWKH2BsOerJ2tduoCkOHPXWa0S/OYtT2dfBSruk4gpSyKKRl2FK9C74Y9m5f7RixnObCL7U555uliE="
    - SUBMIT_CODECOV: false
    - BUILD_DOCS: false
    - GH_REF: github.com/dmgav/test-doc.git

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: BUILD_DOCS=true SUBMIT_CODECOV=true NUMPY=1.17
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6 NUMPY=1.17
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 NUMPY=1.17

python:
  - 3.6
  - 3.7

env:
  - NUMPY=1.17

before_install:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        arch="Linux"
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        arch="MacOSX"
    else
        echo "Unknown arch $TRAVIS_OS_NAME"
        exit 1
    fi
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${arch}-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p ~/mc
    source ~/mc/etc/profile.d/conda.sh
    conda update conda --yes
    export CONDARC=ci/condarc

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -y -n testenv python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY
  - conda activate testenv
  - conda install -y scikit-beam -c nsls2forge
  - conda update -y scikit-beam -c nsls2forge
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install .
  - conda list
  - pip list

script:
- python -c "import platform; import os; ver_installed = platform.python_version();
  ver_requested = os.environ['TRAVIS_PYTHON_VERSION'];
  assert ver_installed.startswith(f'{ver_requested}.');"
- python -c "import numpy; import os; ver_installed = numpy.__version__;
  ver_requested = os.environ['NUMPY'];
  assert ver_installed.startswith(f'{ver_requested}.')"
- flake8
- coverage run run_tests.py
- coverage report -m
- |
  set -e  # If any of the following steps fail, just stop at that point.
  if [ $BUILD_DOCS == 'true' ]; then
    pip install -r requirements-docs.txt
    make -C docs html  # Build the documentation.
    doctr deploy --built-docs docs/_build/html .  # Publish the documentation.
  fi

after_success:
  #- if [ $SUBMIT_CODECOV == 'true' ]; then codecov; fi;
