name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  build:

    if: github.repository == 'dmgav/test_doc'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install redis
        sudo apt install nodejs  # For deployment
        sudo npm install -g --silent gh-pages@2.0.1   # For deployment
        python -m pip install --upgrade pip
        pip install numpy
        pip install .
        pip install -r requirements-dev.txt
        pip list
    - name: Build Docs
      run: |
        pip install -r requirements-docs.txt
        make -C docs html  # Build the documentation.
        # Disable Jekyll theme
        touch docs/_build/html/.nojekyll
    - name: Install and configure dependencies
      run: |
        git config user.email ${GITHUB_ACTOR}@bots.github.com
        git config user.name ${GITHUB_ACTOR}
        echo "CACHE_DIR=/tmp/node" >> $GITHUB_ENV
    - name: Deploy Docs
      env:
        REPO_URI: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dmgav/test_doc.git"
      run: |
        gh-pages --repo ${REPO_URI} --dist docs/_build/html --dotfiles
